// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bztxcfdcetrrszzjfdjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6dHhjZmRjZXRycnN6empmZGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDU2NzAsImV4cCI6MjA1NDgyMTY3MH0.NoieRZ_qGb4n4YB4jk-B1y0sA2w9_H8w7RVIBQEHFKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);